import SideBar from "@/components/admin/layout/sidebar";
import React from "react";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/admin/layout/navbar";
import type { Metadata } from "next";


export const metadata: Metadata  = {
  title: "Ruetta - admin",
  description: "Generated by create next app", //DESCRIZIONE DA MODIFICARE 
};

function layout({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <SideBar />
      <Navbar />
      <div className="w-full xl:w-[calc(100%-288px)] lg:w-[calc(100%-208px)] md:w-[calc(100%-144px)] xl:ml-72 lg:ml-52 md:ml-36">
        <div className="mt-20 z-[10] p-6">
          {children}
        </div>
      </div>
    </SessionProvider>
  );
}

export default layout;
